### ISSUE TITLE
E-mail throw a InvalidDataTypeValueException

### ISSUE THREAD

**Issue by rafaeltpires** [lunarphp/lunar#1286]
- Lunar version: 0.6.1 ( tried with 0.4.x and 0.5.x )
- Laravel Version: 10.25.2
- PHP Version: 8.2.0
- Database Driver & Version: MySQL 8.x

### Expected Behaviour:

Don't throw a InvalidDataTypeValueException and update the order

### Actual Behaviour:

Throw a InvalidDataTypeValueException

![imagem](https://github.com/lunarphp/lunar/assets/21269035/bc596def-57aa-49e8-8f15-79b730efc793)

### Steps To Reproduce:

1- Create a Tax and Tax Zone
![imagem](https://github.com/lunarphp/lunar/assets/21269035/20e385d3-386b-46ce-b82f-34cecb6309aa)

2- Create a Mailable ( i'm using the one with Markdown )

```
<x-mail::message>
    # {{__('Dear')}},

    ## {{ __('We would like to inform you that your order number')}} {{$order->reference}} {{ __('has been shipped') }}

@if($content ?? null)
### Additional notes
{{ $content }}
@endif

{{  __('Thanks') }},<br>
{{ config('app.name') }}
</x-mail::message>
```

3 - Add Mailable to status on config/lunar/orders.php

```php
'dispatched' => [
            'label' => 'Dispatched',
            'color' => '#7fffd4',
            'mailers' => [
                App\Mail\OrderDispatched::class,
            ],
            'notifications' => [],
        ],
```
 
4 - Update the Order Status on Hub with mail 

![imagem](https://github.com/lunarphp/lunar/assets/21269035/0e51c336-627e-48e9-8a0b-5cf7582eb870)

Trace:
```
Lunar\Exceptions\InvalidDataTypeValueException: Value was &quot;object&quot; expected &quot;int&quot; in file /home/vagrant/Projects/a-catedral/vendor/lunarphp/lunar/packages/core/src/DataTypes/Price.php on line 22

#0 /home/vagrant/Projects/a-catedral/vendor/lunarphp/lunar/packages/core/src/Base/Casts/TaxBreakdown.php(29): Lunar\DataTypes\Price-&gt;__construct()
#1 [internal function]: Lunar\Base\Casts\TaxBreakdown-&gt;Lunar\Base\Casts\{closure}()
#2 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
#3 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\Support\Arr::map()
#4 /home/vagrant/Projects/a-catedral/vendor/lunarphp/lunar/packages/core/src/Base/Casts/TaxBreakdown.php(27): Illuminate\Support\Collection-&gt;map()
#5 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(815): Lunar\Base\Casts\TaxBreakdown-&gt;get()
#6 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(791): Illuminate\Database\Eloquent\Model-&gt;getClassCastableAttributeValue()
#7 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(286): Illuminate\Database\Eloquent\Model-&gt;castAttribute()
#8 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(205): Illuminate\Database\Eloquent\Model-&gt;addCastAttributesToArray()
#9 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1636): Illuminate\Database\Eloquent\Model-&gt;attributesToArray()
#10 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1665): Illuminate\Database\Eloquent\Model-&gt;toArray()
#11 [internal function]: Illuminate\Database\Eloquent\Model-&gt;jsonSerialize()
#12 /home/vagrant/Projects/a-catedral/vendor/spatie/flare-client-php/src/Truncation/ReportTrimmer.php(41): json_encode()
#13 /home/vagrant/Projects/a-catedral/vendor/spatie/flare-client-php/src/Truncation/ReportTrimmer.php(24): Spatie\FlareClient\Truncation\ReportTrimmer-&gt;needsToBeTrimmed()
#14 /home/vagrant/Projects/a-catedral/vendor/spatie/laravel-ray/src/Watchers/ExceptionWatcher.php(68): Spatie\FlareClient\Truncation\ReportTrimmer-&gt;trim()
#15 /home/vagrant/Projects/a-catedral/vendor/spatie/laravel-ray/src/Watchers/ExceptionWatcher.php(37): Spatie\LaravelRay\Watchers\ExceptionWatcher-&gt;getFlareReport()
#16 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Spatie\LaravelRay\Watchers\ExceptionWatcher-&gt;Spatie\LaravelRay\Watchers\{closure}()
#17 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher-&gt;Illuminate\Events\{closure}()
#18 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Log/Logger.php(248): Illuminate\Events\Dispatcher-&gt;dispatch()
#19 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Log/Logger.php(189): Illuminate\Log\Logger-&gt;fireLogEvent()
#20 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Log/Logger.php(97): Illuminate\Log\Logger-&gt;writeLog()
#21 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(665): Illuminate\Log\Logger-&gt;error()
#22 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(317): Illuminate\Log\LogManager-&gt;error()
#23 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(278): Illuminate\Foundation\Exceptions\Handler-&gt;reportThrowable()
#24 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(497): Illuminate\Foundation\Exceptions\Handler-&gt;report()
#25 /home/vagrant/Projects/a-catedral/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel-&gt;reportException()
#26 /home/vagrant/Projects/a-catedral/public/index.php(51): Illuminate\Foundation\Http\Kernel-&gt;handle()
#27 {main}
```

- After some digging i belive the Tax Breakdown is being serialized 2 times.
- The E-mail is sended but the status isn't updated
![imagem](https://github.com/lunarphp/lunar/assets/21269035/28ffa54d-3661-4d16-b7f8-563dd953125b)

Thank you and great work!

**Comment by rafaeltpires** [comment]
@alecritson problem solved with 0.7, Arigato!
